// ── DICTIONARY — All words from the document ─────────────────
const WORDS = [
  // A
  "able","about","above","abroad","absent","accept","accident","across","act","action",
  "active","activity","actor","actress","actually","add","address","admire","adult","advertisement",
  "advice","advise","affect","afraid","after","afternoon","again","against","age","ago",
  "agree","ahead","aim","air","airline","airplane","plane","airport","alarm","album",
  "alike","alive","all","allow","almost","alone","along","aloud","alphabet","already",
  "also","altogether","always","ambulance","america","american","among","amount","ancient","and",
  "angel","anger","angry","ankle","animal","another","answer","ant","any","anyone",
  "anybody","anything","anywhere","apartment","apologize","appear","apple","appreciate","april","area",
  "argue","arm","armchair","army","around","arrange","arrive","art","artist","ask",
  "asleep","assistant","assume","attack","attention","august","aunt","autumn","fall","available",
  "avoid","away",
  // B
  "baby","back","backpack","backward","bad","badminton","bag","bake","bakery","balcony",
  "ball","balloon","banana","band","bank","barbecue","barber","bark","base","baseball",
  "basement","basic","basket","basketball","bat","bath","bathe","bathroom","beach","bean",
  "bear","beard","beat","beautiful","beauty","because","become","bed","bedroom","bee",
  "beef","beer","before","begin","beginner","beginning","behave","behind","believe","bell",
  "belong","below","belt","bench","beside","besides","between","beyond","bicycle","bike",
  "big","bill","biology","bird","birthday","bite","bitter","black","blackboard","blame",
  "blank","blanket","bless","blind","block","blood","blouse","blow","blue","board",
  "boat","body","boil","bomb","bone","book","bookcase","bookstore","bored","boring",
  "born","borrow","boss","both","bother","bottle","bottom","bow","bowl","bowling",
  "box","boy","branch","brave","bread","break","breakfast","brick","bridge","bright",
  "bring","broad","broadcast","brother","brown","brunch","brush","bucket","buffet","bug",
  "build","building","bun","bundle","burger","burn","burst","bus","business","businessman",
  "busy","butter","butterfly","button","buy",
  // C
  "cabbage","cable","cafeteria","cage","cake","calendar","call","calm","camera","camp",
  "campus","cancel","cancer","candle","candy","cap","captain","car","card","care",
  "careful","careless","carpet","carrot","carry","cartoon","case","cash","cassette","castle",
  "cat","catch","cause","ceiling","celebrate","cellphone","cent","center","centimeter","central",
  "century","cereal","certain","chair","chalk","chance","change","channel","character","charge",
  "chart","chase","cheap","cheat","check","cheer","cheese","chemistry","chess","chicken",
  "child","childhood","childish","childlike","chin","china","chinese","chocolate","choice","choose",
  "chopsticks","christmas","chubby","church","circle","city","clap","class","classical","classmate",
  "classroom","clean","clear","clerk","clever","climate","climb","clock","close","closet",
  "clothes","cloud","cloudy","club","coach","coast","coat","cockroach","coffee","coin",
  "cola","cold","collect","college","color","colorful","comb","come","comfortable","comic",
  "command","comment","common","company","compare","complain","complete","computer","concern","confident",
  "confuse","congratulation","consider","considerate","continue","contract","control","convenient","conversation","cook",
  "cookie","cool","copy","corn","corner","correct","cost","cotton","couch","cough",
  "count","country","couple","courage","course","court","cousin","cover","cow","cowboy",
  "crab","crayon","crazy","cream","create","crime","cross","crowd","crowded","cruel",
  "cry","culture","cup","cure","curious","current","curtain","curve","custom","customer","cut","cute",
  // D
  "daily","damage","dance","danger","dangerous","dark","date","daughter","dawn","day",
  "dead","deaf","deal","dear","death","debate","december","decide","decision","decorate",
  "decrease","deep","deer","degree","delicious","deliver","dentist","department","depend","describe",
  "desert","design","desire","desk","dessert","detect","develop","dial","diamond","diary",
  "dictionary","die","diet","difference","different","difficult","difficulty","dig","diligent","diplomat",
  "dinner","dinosaur","direct","direction","dirty","disappear","discover","discuss","discussion","dish",
  "dishonest","distance","distant","divide","dizzy","doctor","dodge","dog","doll","dollar",
  "dolphin","donkey","door","dot","double","doubt","doughnut","down","downstairs","downtown",
  "dozen","dragon","drama","draw","drawer","dream","dress","dresser","drink","drive",
  "driver","drop","drugstore","drum","dry","dryer","duck","dumb","dumpling","during","duty",
  // E
  "each","eagle","ear","early","earn","earrings","earth","ease","east","easter",
  "easy","eat","edge","education","effort","egg","eight","eighteen","eighty","either",
  "elder","elect","elephant","eleven","electric","else","email","embarrass","emotion","emphasize",
  "employ","empty","end","enemy","energetic","energy","engine","engineer","english","enjoy",
  "enough","enter","entrance","envelope","environment","envy","equal","eraser","error","especially",
  "eve","even","evening","event","ever","every","everyone","everybody","everything","everywhere",
  "evil","exam","example","excellent","except","excite","excited","exciting","excuse","exercise",
  "exist","exit","expect","expensive","experience","explain","express","extra","eye",
  // F
  "face","fact","factory","fail","fair","false","family","famous","fan","fancy",
  "fantastic","far","farm","farmer","fashionable","fast","fat","father","dad","daddy",
  "faucet","fault","favorite","fear","february","fee","feed","feel","feeling","female",
  "fence","festival","fever","few","fifteen","fifty","fight","fill","film","final",
  "finally","find","fine","finger","finish","fire","first","fish","fisherman","fit",
  "five","fix","flag","flashlight","flat","flight","floor","flour","flower","flu",
  "flute","fly","focus","fog","foggy","follow","food","fool","foolish","foot",
  "football","foreign","foreigner","forest","forget","forgive","fork","form","formal","former",
  "forty","forward","four","fourteen","fox","frank","free","freedom","freezer","freezing",
  "fresh","friday","friend","friendly","friendship","frighten","frisbee","frog","front","fruit",
  "fry","full","fun","funny","furniture","future",
  // G
  "gain","game","garage","garden","garbage","gas","gate","gather","general","generous",
  "genius","gentle","gentleman","geography","gesture","get","ghost","giant","gift","girl",
  "give","glad","glass","glasses","glove","glue","go","goal","goat","god",
  "gold","golden","golf","good","goodbye","bye","goodness","goose","government","grade",
  "gram","granddaughter","grandfather","grandpa","grandmother","grandma","grandson","grape","grass","gray",
  "great","greedy","green","greet","ground","group","grow","guard","guava","guess",
  "guest","guide","guitar","gun","guy","gym",
  // H
  "habit","hair","haircut","half","hall","halloween","ham","hamburger","hammer","hand",
  "handkerchief","handle","handsome","hang","hanger","happen","happy","hard","hardly","hat",
  "hate","have","has","had","head","headache","health","healthy","hear","heart",
  "heat","heater","heavy","height","helicopter","hello","help","helpful","hen","here",
  "hero","hey","hi","hide","high","highway","hike","hill","hip","hippo",
  "hire","history","hit","hobby","hold","hole","holiday","home","homesick","homework",
  "honest","honesty","honey","hop","hope","horrible","horse","hospital","host","hot",
  "hotel","hour","house","housewife","housework","how","however","hug","human","humble",
  "humid","humor","humorous","hundred","hunger","hungry","hunt","hunter","hurry","hurt","husband",
  // I
  "ice","idea","if","ignore","ill","imagine","impolite","importance","important","impossible",
  "improve","inch","include","income","increase","independent","indicate","influence","information","ink",
  "insect","inside","insist","inspire","instant","instrument","intelligent","interest","interested","interesting",
  "international","internet","interrupt","interview","into","introduce","invent","invitation","invite","iron",
  "island",
  // J
  "jacket","jam","january","jazz","jealous","jeans","jeep","job","jog","join",
  "joke","journalist","joy","judge","juice","july","jump","june","just",
  // K
  "kangaroo","keep","ketchup","key","kick","kid","kill","kilogram","kilometer","kind",
  "kindergarten","king","kingdom","kiss","kitchen","kite","kitten","knee","knife","knock",
  "know","knowledge","koala",
  // L
  "lack","DAA","lake","lamb","lamp","land","language","lantern","large","last",
  "late","later","latest","latter","laugh","law","lawyer","lay","lazy","lead",
  "leader","leaf","learn","least","leave","left","leg","lemon","lend","less",
  "lesson","let","letter","lettuce","level","library","lick","lid","lie","life",
  "lift","light","lightning","like","likely","limit","line","link","lion","lip",
  "liquid","list","listen","liter","little","live","loaf","local","lock","locker",
  "lonely","long","look","lose","loser","loud","love","lovely","low","lucky","lunch",
  // M
  "machine","mad","magazine","magic","magician","mail","mailman","main","major","make",
  "male","mall","man","manager","mango","manner","many","map","march","mark",
  "marker","market","marry","married","marvelous","mask","mass","master","match","math",
  "mathematics","matter","maximum","may","meal","mean","meaning","measure","meat","mechanic",
  "medicine","medium","meet","meeting","member","memory","menu","message","metal","meter",
  "method","microwave","middle","midnight","mile","milk","million","mind","minor","minus",
  "minute","mirror","miss","mistake","mix","model","modern","moment","monday","money",
  "monkey","monster","month","moon","morning","mop","mosquito","most","mother","mom",
  "mommy","motion","motorcycle","mountain","mouse","mouth","move","movement","movie","much",
  "mud","museum","music","musician","must",
  // N
  "nail","name","napkin","narrow","nation","national","natural","nature","naughty","near",
  "nearly","necessary","neck","necklace","need","needle","negative","neighbor","neither","nephew",
  "nervous","nest","net","never","new","news","newspaper","next","nice","niece",
  "night","nine","nineteen","ninety","nobody","nod","noise","noisy","none","noodle",
  "noon","north","nose","note","notebook","nothing","notice","novel","november","now",
  "number","nurse","nut",
  // O
  "obey","object","ocean","october","offer","office","officer","often","oil","old",
  "omit","once","one","oneself","onion","only","open","operation","opinion","orange",
  "order","ordinary","other","outside","oven","over","overpass","overseas","own","owner","ox",
  // P
  "pack","package","page","pain","painful","paint","painter","pair","pajamas","pale",
  "pan","panda","pants","papaya","paper","pardon","parent","park","parrot","part",
  "partner","party","pass","passenger","past","paste","path","patient","pattern","pause",
  "pay","peace","peaceful","peach","pear","pen","pencil","people","pepper","perfect",
  "perhaps","period","person","personal","pet","photo","physics","piano","pick","picnic",
  "picture","pie","piece","pig","pigeon","pile","pillow","pin","pineapple","pink",
  "pipe","pizza","place","plain","plan","planet","plant","plate","platform","play",
  "player","playground","pleasant","please","pleased","pleasure","plus","pocket","poem","point",
  "poison","police","polite","pollute","pollution","pond","pool","poor","popcorn","popular",
  "population","pork","position","positive","possible","postcard","pot","potato","pound","powder",
  "power","practice","praise","pray","precious","prepare","present","president","pressure","pretty",
  "price","priest","primary","prince","princess","principal","principle","print","printer","private",
  "prize","probably","problem","produce","production","professor","program","progress","project","promise",
  "pronounce","protect","proud","provide","public","pull","pump","pumpkin","punish","puppy",
  "purple","purpose","purse","push","put","puzzle",
  // Q
  "quarter","queen","question","quick","quiet","quit","quite","quiz",
  // R
  "rabbit","race","radio","railroad","railway","rain","rainbow","raincoat","rainy","raise",
  "rare","rat","rather","reach","read","ready","real","realize","really","reason",
  "receive","record","recorder","recover","rectangle","recycle","red","refrigerator","refuse","regret",
  "regular","reject","relative","remember","remind","rent","repair","repeat","report","reporter",
  "respect","responsible","rest","restaurant","restroom","result","return","review","revise","rice",
  "rich","ride","right","ring","rise","river","road","rob","robot","rock",
  "role","roll","roof","room","root","rope","rose","round","row","rub",
  "rubber","rude","ruin","rule","ruler","run","rush",
  // S
  "sad","safe","safety","sail","sailor","salad","sale","salesman","salt","same",
  "sample","sand","sandwich","satisfy","saturday","save","say","scared","scarf","scene",
  "scenery","school","science","scientist","scooter","score","screen","sea","seafood","search",
  "season","seat","second","secret","secretary","section","see","seed","seek","seem",
  "seesaw","seldom","select","selfish","sell","semester","send","sense","sentence","september",
  "serious","servant","serve","service","set","seven","seventeen","seventy","several","shake",
  "shape","share","shark","sharp","sheep","sheet","shelf","shine","ship","shirt",
  "shoe","shop","shopkeeper","shoot","shore","short","shorts","shoulder","shout","show",
  "shower","shrimp","shut","shy","sick","side","sidewalk","sight","sign","silence",
  "silent","silly","silver","similar","simple","since","sincere","sing","singer","single",
  "sink","sister","sit","six","sixteen","sixty","size","skate","ski","skill",
  "skillful","skin","skinny","skirt","sky","sleep","sleepy","slender","slice","slide",
  "slim","slippers","slow","small","smart","smell","smile","smoke","snack","snail",
  "snake","sneakers","sneaky","snow","snowman","snowy","soap","soccer","social","society",
  "socks","soda","sofa","soldier","solve","someone","somebody","something","sometimes","somewhere",
  "son","song","soon","sore","sorry","soul","sound","soup","sour","south",
  "space","spaghetti","speak","speaker","special","speech","speed","spell","spend","spider",
  "spirit","spoon","sports","spot","spread","spring","square","stairs","stamp","stand",
  "star","start","state","station","stationery","stay","steak","steal","steam","step",
  "still","stingy","stomach","stomachache","stone","stop","store","storm","stormy","story",
  "stove","straight","strange","stranger","straw","strawberry","stream","street","strike","strong",
  "student","study","stupid","style","subject","subway","succeed","success","successful","such",
  "sudden","sugar","suggest","suit","summer","sun","sunday","sunny","super","supermarket",
  "supper","support","sure","surf","surprise","surprised","survive","swallow","swan","sweater",
  "sweep","sweet","swim","swimsuit","swing","symbol","system",
  // T
  "table","tail","taiwan","take","talent","talk","talkative","tall","tangerine","tank",
  "tape","taste","taxi","tea","teach","teacher","team","teapot","tear","teenager",
  "telephone","phone","television","tell","temperature","temple","ten","tennis","tent","term",
  "terrible","terrific","test","textbook","thank","thanksgiving","theater","then","there","therefore",
  "thick","thief","thin","thing","think","third","thirsty","thirteen","thirty","thought",
  "thousand","three","throat","throw","thumb","thunder","thursday","ticket","tidy","tie",
  "tiger","time","tiny","tip","tired","title","toast","today","toe","tofu",
  "together","toilet","tomato","tomorrow","tongue","tonight","too","tool","tooth","toothache",
  "toothbrush","top","topic","total","touch","toward","towel","tower","town","toy",
  "trace","trade","tradition","traditional","traffic","train","trap","trash","travel","treasure",
  "treat","tree","triangle","trick","trip","trouble","trousers","truck","true","trumpet",
  "trust","truth","try","tub","tube","tuesday","tunnel","turkey","turn","turtle",
  "twelve","twenty","twice","two","type","typhoon",
  // U
  "ugly","umbrella","uncle","under","underline","underpass","understand","underwear","unhappy","uniform",
  "unique","universe","university","until","upper","upstairs","use","useful","usual","usually",
  // V
  "vacation","valentine","valley","valuable","value","vegetable","vendor","very","vest","victory",
  "video","village","vinegar","violin","visit","visitor","vocabulary","voice","volleyball","vote",
  // W
  "waist","wait","waiter","waitress","wake","walk","wall","wallet","want","war",
  "warm","wash","waste","watch","water","waterfall","watermelon","wave","way","weak",
  "wear","weather","wedding","wednesday","week","weekday","weekend","weight","welcome","well",
  "west","wet","whale","wheel","white","wide","wife","wild","win","wind",
  "window","windy","wing","winner","winter","wise","wish","wood","woods","word",
  "work","workbook","worker","world","worm","worry","wound","wrist","write","writer","wrong",
  // Y
  "yard","year","yell","yellow","yes","yesterday","yet","young","youth","yummy",
  // Z
  "zebra","zero","zoo",
  // Extra - tech/CS words from original list
  "algorithm","application","array","binary","bubble","cache","callback","cascade","certificate","class",
  "cluster","compile","component","condition","config","connect","container","content","context","controller",
  "convert","cookie","copy","core","count","create","cursor","cycle","daemon","database",
  "debug","decimal","declare","default","delete","deploy","detect","dictionary","directory","disconnect",
  "dispatch","display","divide","document","domain","download","driver","dynamic","encrypt","endpoint",
  "engine","enum","environment","error","evaluate","event","execute","exists","export","expression",
  "extension","external","factory","feature","fetch","field","filter","flag","flow","format",
  "framework","function","generate","global","graph","hash","heap","hierarchy","host","html",
  "http","identifier","import","increment","index","initialize","input","insert","install","integer",
  "integrate","interface","internal","internet","invoke","iterate","iterator","java","javascript","json",
  "kernel","keyword","kotlin","lambda","layer","linear","link","list","local","logic",
  "loop","machine","manage","map","matrix","memory","merge","method","mobile","model",
  "module","monitor","mutex","namespace","nested","network","node","notification","null","object",
  "operator","output","package","parameter","parse","password","path","pattern","payload","permission",
  "pipeline","pixel","pointer","polygon","pool","port","post","prefix","primitive","print",
  "private","process","program","project","property","protected","protocol","proxy","public","publish",
  "python","queue","random","react","record","recursion","reduce","reference","register","release",
  "remove","render","request","resolve","response","restart","return","reverse","role","route",
  "runtime","schema","scope","script","segment","select","sequence","server","service","session",
  "shell","signal","simple","socket","software","sort","source","space","stack","static",
  "status","stream","string","struct","structure","success","swap","switch","sync","syntax",
  "table","target","task","technology","template","terminal","test","text","theme","thread",
  "timeout","toggle","token","transaction","transfer","transform","traverse","trigger","truncate","tuple",
  "type","union","unit","unix","update","upload","url","user","username","utility",
  "validate","value","variable","vector","version","view","visual","web","website","window",
  "workflow","xml","yaml"
];
